"""
Provenance Guard — AI Content Attribution API
Flask backend for detecting and labeling AI-generated vs. human-written content.

Endpoints:
    POST /submit     — analyze text and return attribution label
    POST /appeal     — flag a disputed verdict for human review
    GET  /log        — retrieve recent submission records
    GET  /analytics  — detection patterns, appeal rate, average confidence
    GET  /health     — service health check

Usage:
    python app.py
"""

import json
import os
import re
import sqlite3
import statistics
import uuid
from datetime import datetime
from flask import Flask, request, jsonify
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address
from groq import Groq
from dotenv import load_dotenv

load_dotenv()

app = Flask(__name__)

limiter = Limiter(
    get_remote_address,
    app=app,
    storage_uri="memory://"
)

_groq_client = None


def get_groq_client():
    global _groq_client
    if _groq_client is None:
        api_key = os.environ.get("GROQ_API_KEY")
        if not api_key:
            return None
        _groq_client = Groq(api_key=api_key)
    return _groq_client

DB_PATH = "provenance.db"


def init_db():
    conn = sqlite3.connect(DB_PATH)
    c = conn.cursor()
    c.execute("""
        CREATE TABLE IF NOT EXISTS submissions (
            content_id TEXT PRIMARY KEY,
            creator_id TEXT,
            timestamp TEXT,
            attribution TEXT,
            confidence REAL,
            llm_score REAL,
            stylometric_score REAL,
            modal_score REAL,
            status TEXT,
            appeal_reasoning TEXT
        )
    """)
    conn.commit()
    conn.close()


def log_submission(content_id, creator_id, timestamp, attribution, confidence, llm_score, stylometric_score, modal_score, status):
    conn = sqlite3.connect(DB_PATH)
    c = conn.cursor()
    c.execute("""
        INSERT INTO submissions (content_id, creator_id, timestamp, attribution, confidence, llm_score, stylometric_score, modal_score, status, appeal_reasoning)
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
    """, (content_id, creator_id, timestamp, attribution, confidence, llm_score, stylometric_score, modal_score, status, None))
    conn.commit()
    conn.close()


def update_appeal(content_id, reasoning):
    conn = sqlite3.connect(DB_PATH)
    c = conn.cursor()
    c.execute("""
        UPDATE submissions SET status = 'under_review', appeal_reasoning = ? WHERE content_id = ?
    """, (reasoning, content_id))
    affected = c.rowcount
    conn.commit()
    conn.close()
    return affected


def get_log_entries():
    conn = sqlite3.connect(DB_PATH)
    c = conn.cursor()
    c.execute("""
        SELECT content_id, creator_id, timestamp, attribution, confidence, llm_score, stylometric_score, modal_score, status, appeal_reasoning
        FROM submissions ORDER BY timestamp DESC LIMIT 20
    """)
    rows = c.fetchall()
    conn.close()
    keys = ["content_id", "creator_id", "timestamp", "attribution", "confidence", "llm_score", "stylometric_score", "modal_score", "status", "appeal_reasoning"]
    return [dict(zip(keys, row)) for row in rows]


def llm_signal(text):
    try:
        client = get_groq_client()
        if client is None:
            return 0.5
        response = client.chat.completions.create(
            model="llama-3.3-70b-versatile",
            messages=[
                {
                    "role": "system",
                    "content": (
                        "You are an AI content detection expert. Analyze the given text and estimate "
                        "the probability that it was generated by an AI system rather than written by a human. "
                        "Respond with ONLY a JSON object in this exact format: {\"ai_probability\": 0.85} "
                        "where the value is a float between 0.0 (definitely human) and 1.0 (definitely AI)."
                    )
                },
                {
                    "role": "user",
                    "content": f"Analyze this text and return the ai_probability JSON:\n\n{text}"
                }
            ],
            temperature=0.1,
            max_tokens=50
        )
        raw = response.choices[0].message.content.strip()
        data = json.loads(raw)
        score = float(data.get("ai_probability", 0.5))
        return max(0.0, min(1.0, score))
    except Exception:
        return 0.5


def stylometric_signal(text):
    sentences = re.split(r'[.!?]+', text)
    sentences = [s.strip() for s in sentences if s.strip()]

    # Metric 1: Sentence length variance
    # AI text tends to produce uniformly structured sentences → lower variance → higher AI score.
    # Normalize against 100 (human prose regularly exceeds 40 with just a few sentences).
    if len(sentences) >= 2:
        lengths = [len(s.split()) for s in sentences]
        variance = statistics.variance(lengths)
        variance_score = max(0.0, min(1.0, 1.0 - (variance / 100.0)))
    else:
        variance_score = 0.5

    # Metric 2: Type-token ratio (vocabulary diversity)
    # Lower TTR → more repetitive vocabulary → more AI-like.
    # Normalize over full [0, 1] range so high-TTR text is not prematurely clamped to 0.
    words = re.findall(r'\b\w+\b', text.lower())
    if len(words) > 0:
        ttr = len(set(words)) / len(words)
        ttr_score = max(0.0, min(1.0, 1.0 - ttr))
    else:
        ttr_score = 0.5

    # Metric 3: Punctuation density (weighted double — most reliable discriminator)
    # Human writers use more varied punctuation (em dashes, semicolons, parentheses, ellipses).
    # Density above 3 per 100 chars is treated as fully human-like.
    varied_punct = len(re.findall(r'[;:\-\(\)\[\]…""—–]', text))
    total_chars = max(len(text), 1)
    punct_density = varied_punct / total_chars * 100
    punct_score = max(0.0, min(1.0, 1.0 - (punct_density / 3.0)))

    # Punctuation is weighted 2x because it is the most reliable discriminator.
    combined = (variance_score + ttr_score + punct_score * 2) / 4.0
    return round(combined, 4)


def modal_verb_signal(text):
    """
    Signal 3: Modal verb density.
    AI-generated text overuses hedging modals (would, could, may, might, should, can)
    as a stylistic hedge. High density → more AI-like.
    Normalized: density > 6 per 100 words → fully AI-like (score 1.0).
    """
    words = re.findall(r'\b\w+\b', text.lower())
    if not words:
        return 0.5
    modals = {"would", "could", "may", "might", "should", "can", "shall", "must", "ought"}
    modal_count = sum(1 for w in words if w in modals)
    density = modal_count / len(words) * 100  # per 100 words
    # Normalize: density >= 6 → fully AI-like (1.0); 0 → 0.0
    score = min(1.0, density / 6.0)
    return round(score, 4)


def combine_signals(llm_score, stylometric_score, modal_score):
    """
    Ensemble: 3 signals with documented weights.
    LLM (50%): broadest semantic pattern recognition, most reliable.
    Stylometric (30%): structural/surface properties, fast and deterministic.
    Modal verb (20%): hedging language density, catches a specific AI tell.
    Conflicts: majority vote of direction (>0.5 vs <0.5) breaks ties implicitly
    via the weighted average — no single signal can override both others.
    """
    return round(llm_score * 0.5 + stylometric_score * 0.3 + modal_score * 0.2, 4)


def get_label(confidence, attribution):
    pct = round(confidence * 100)
    if attribution == "likely_ai":
        return (
            f"Looks like AI-generated content ({pct}% confidence). "
            f"Our system detected patterns commonly found in AI writing. "
            f"If you used an AI tool to help write this, consider adding a note so readers know. "
            f"Think this is wrong? You can file an appeal."
        )
    elif attribution == "likely_human":
        return (
            f"Looks like human-written content ({pct}% confidence). "
            f"Our system found strong signs that a person wrote this — "
            f"things like natural variation in sentence length and personal punctuation habits. "
            f"Great news for your attribution!"
        )
    else:
        return (
            f"We're not sure about this one ({pct}% confidence). "
            f"The writing has some qualities our system associates with AI and some it associates with humans. "
            f"That can happen with carefully edited work or content that crosses genres. "
            f"If you wrote this yourself, you can file an appeal and tell us why."
        )


init_db()


@app.route("/submit", methods=["POST"])
@limiter.limit("10 per minute;100 per day")
def submit():
    data = request.get_json()
    if not data:
        return jsonify({"error": "Request body must be JSON"}), 400

    text = data.get("text", "").strip()
    creator_id = data.get("creator_id", "").strip()

    if not text:
        return jsonify({"error": "Missing required field: text"}), 400
    if not creator_id:
        return jsonify({"error": "Missing required field: creator_id"}), 400

    content_id = str(uuid.uuid4())
    timestamp = datetime.utcnow().isoformat() + "Z"

    llm_score = llm_signal(text)
    stylometric_score = stylometric_signal(text)
    modal_score = modal_verb_signal(text)
    confidence = combine_signals(llm_score, stylometric_score, modal_score)

    if confidence > 0.70:
        attribution = "likely_ai"
    elif confidence < 0.35:
        attribution = "likely_human"
    else:
        attribution = "uncertain"

    label = get_label(confidence, attribution)
    status = "reviewed"

    log_submission(content_id, creator_id, timestamp, attribution, confidence, llm_score, stylometric_score, modal_score, status)

    return jsonify({
        "content_id": content_id,
        "creator_id": creator_id,
        "attribution": attribution,
        "confidence": confidence,
        "signals": {
            "llm_score": llm_score,
            "stylometric_score": stylometric_score,
            "modal_score": modal_score
        },
        "label": label,
        "status": status,
        "timestamp": timestamp
    })


@app.route("/appeal", methods=["POST"])
def appeal():
    data = request.get_json()
    if not data:
        return jsonify({"error": "Request body must be JSON"}), 400

    content_id = data.get("content_id", "").strip()
    creator_reasoning = data.get("creator_reasoning", "").strip()

    if not content_id:
        return jsonify({"error": "Missing required field: content_id"}), 400
    if not creator_reasoning:
        return jsonify({"error": "Missing required field: creator_reasoning"}), 400

    affected = update_appeal(content_id, creator_reasoning)
    if affected == 0:
        return jsonify({"error": f"Content not found: {content_id}"}), 404

    return jsonify({
        "message": "Appeal submitted successfully. A human reviewer will examine your case.",
        "content_id": content_id,
        "status": "under_review"
    })


def get_analytics_data():
    conn = sqlite3.connect(DB_PATH)
    c = conn.cursor()
    c.execute("SELECT attribution, confidence, status FROM submissions")
    rows = c.fetchall()
    conn.close()
    return rows


@app.route("/analytics", methods=["GET"])
def analytics():
    rows = get_analytics_data()
    if not rows:
        return jsonify({"message": "No submissions yet", "metrics": {}})

    total = len(rows)
    counts = {"likely_ai": 0, "likely_human": 0, "uncertain": 0}
    appeal_count = 0
    confidence_sum = 0.0

    for attribution, confidence, status in rows:
        counts[attribution] = counts.get(attribution, 0) + 1
        if status == "under_review":
            appeal_count += 1
        confidence_sum += confidence or 0.0

    return jsonify({
        "total_submissions": total,
        "detection_distribution": {
            "likely_ai": counts["likely_ai"],
            "likely_human": counts["likely_human"],
            "uncertain": counts["uncertain"],
            "ai_ratio": round(counts["likely_ai"] / total, 3),
            "human_ratio": round(counts["likely_human"] / total, 3),
            "uncertain_ratio": round(counts["uncertain"] / total, 3)
        },
        "appeal_rate": round(appeal_count / total, 3),
        "appeals_filed": appeal_count,
        "average_confidence": round(confidence_sum / total, 3)
    })


@app.route("/log", methods=["GET"])
def log():
    entries = get_log_entries()
    return jsonify({"entries": entries, "count": len(entries)})


@app.route("/health", methods=["GET"])
def health():
    return jsonify({"status": "ok", "service": "provenance-guard"})


if __name__ == "__main__":
    port = int(os.environ.get("PORT", 5001))
    app.run(debug=True, port=port)
